---
kind: pipeline
name: default
type: docker

platform:
  arch: amd64

trigger:
  branch:
  - main

steps:
- name: build
  image: golang
  commands:
  - go build cmd/gitea-bulk-importer/gitea-bulk-exporter.go
  - gitea-bulk-exporter --help